# Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

services:
  # PREFECT WORKER
  worker:
    build:
      context: ./services/worker
    env_file:
      - .env
    volumes:
      - ./flows:/opt/prefect/flows
      - ./core:/opt/prefect/core

  # OBJECT STORAGE
  minio:
    build:
      context: ./services/minio
    env_file:
      - .env
    volumes:
      - "minio:/data"
    ports:
      - "${MINIO_API_PORT}:${MINIO_API_PORT}"
      - "${MINIO_UI_PORT}:${MINIO_UI_PORT}"

  # MLFlow Tracking server
  mlflow:
    build:
      context: ./services/mlflow
    env_file:
      - .env
    ports:
      - "${MLFLOW_TRACKING_PORT}:${MLFLOW_TRACKING_PORT}"

  # Postgres (MLFlow tracking server backend store)
  postgres:
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
     - db:/var/lib/postgresql/data

  # Jupyter lab container
  jupyter:
    build:
      context: ./services/jupyter
    env_file:
      - .env
    volumes:
      - ./flows:/app/flows
      - ./core:/app/core
      - ./notebooks:/app/notebooks
      - ./data:/app/data
    ports:
      - "${JUPYTER_PORT}:${JUPYTER_PORT}"

volumes:
  minio:
  db:
networks:
  default:
    name: df-network
