# Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

services:
  # PREFECT WORKER
  worker:
    build:
      context: ./worker
    environment:
      PREFECT_API_URL: ${PREFECT_API_URL}
      PREFECT_API_KEY: ${PREFECT_API_KEY}
      DF_ENVIRONMENT: ${DF_ENVIRONMENT}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./flows:/opt/prefect/flows

  # OBJECT STORAGE
  minio:
    build:
      context: ./minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - "minio:/data"
    ports:
      - 9000:9000
      - 9001:9001

volumes:
  minio:
