# Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

services:
  # PREFECT WORKER
  worker:
    build:
      context: ./worker
    env_file:
      - .env.local
    volumes:
      - ./flows:/opt/prefect/flows

  # OBJECT STORAGE
  minio:
    build:
      context: ./minio
    env_file:
      - .env.local
    volumes:
      - "minio:/data"
    ports:
      - 9000:9000
      - 9001:9001

volumes:
  minio:
networks:
  default:
    name: df-network
